name: Build Project

# Run workflow on every push to the main branch
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Build .NET Project
      run: dotnet build wasm-blog-engine.csproj -c Release -o release --nologo